# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8e3e5985cc9500430fdd845fc05992ce87f0e216f47375e85f2c75f265627da4c967578fdc673ab45f508426deaf142c6291aa091578f01f305634f95653d2

test:
  secret_key_base: 2acccdff0f13e2ba496f5d5dea4478d8ba2d92d131479bfc9951f5ca1d8a004ed4acc50190d9065a2220ee09ef0c3d71dce1afdc76c202460a77dea23658a397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
